# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "17dd6639f0adf774c19762bfc1f17d24"
application_url = "https://success-powerseller-jewel-cookbook.trycloudflare.com"
embedded = true
name = "nudgenest-shpfy-app"
handle = "nudgenest-shpfy-app"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "https://nudgenest-backend-1094805904049.europe-west1.run.app/api/v1/shopify-webhook"

  [[webhooks.subscriptions]]
  topics = [ "draft_orders/create" ]
  uri = "https://nudgenest-backend-1094805904049.europe-west1.run.app/api/v1/shopify-webhook"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_orders, read_draft_orders"

[auth]
redirect_urls = [
  "https://success-powerseller-jewel-cookbook.trycloudflare.com/auth/callback",
  "https://success-powerseller-jewel-cookbook.trycloudflare.com/auth/shopify/callback",
  "https://success-powerseller-jewel-cookbook.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "nudgenest.myshopify.com"
automatically_update_urls_on_dev = true
